### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by killax2000** [TheLimePixel/Modern-Skyblock-3#615] opened 2018-06-21 18:07 UTC
I can't break any blocks on my island.
I just can create my island.

(Sorry for my bad english I'm french 🤐 )

**Comment by aturneruk** [comment] 2018-06-22 00:09
In the absence of further details, I suspect that this caused by the problems with the update to Ore Excavation. Try reverting Ore Excavation to version 1.4.118.

If this fixes it, then this issue is a duplicate of #610

**Comment by minimalkid1** [comment] 2018-06-23 07:53
Me too! I make a new world, i type: "/island create grass" I spawn on tree and if i break a leaf , it breaks but when i try to go in the place where the leaf it was i glitch a lot and can't enter in this place. if i keep go in front to enter in place where the leaf was sometimes i can for 2 second and again push back like the leaf is still there...

**Comment by quatorhun** [comment] 2018-06-23 10:41
I had the same issue, reverting Ore Excavation solved it, thanks.

**Closed as completed** 2018-06-24 17:45 UTC
Labels: duplicate
