### ISSUE TITLE
Installing the latest version on Twitch throws an 262691 error

### ISSUE THREAD

**Issue by Furious1964** [TheLimePixel/Modern-Skyblock-3#789] opened 2018-10-14 00:41 UTC
**Describe the bug**
Can't install because of this error.

**To Reproduce**
Just install on Twitch.

**Crash Reports**
None.

**Pack Information**
 - Pack version: 3.4.2
 - Pack Mode: n/a
 - SP or MP: n/a
 - Added Mods:

**Screenshots**

**Additional context**

**Comment by UnhallowedDeath** [comment] 2018-10-14 01:28
#785, #782, #784, and mine #788 are also addressing this problem. I don't believe there is a fix that works so far. You could try using the server files to replace the deleted mod that is addressed in #785.

**Comment by Furious1964** [comment] 2018-10-14 01:37
I don't think the server file contains all of the mods used...some my be for client only.

**Comment by UnhallowedDeath** [comment] 2018-10-14 01:41
yeah. that was the suggestion left on my issue figured id pass it on

**Comment by Furious1964** [comment] 2018-10-14 01:51
I'll try it just in case as there's also another MS3 file on the site.

EDIT: THAT WORK!!! Whoever thought of that is a genius. Thank you.

**Comment by UnhallowedDeath** [comment] 2018-10-14 02:25
so how do you get the server files?

**Comment by Furious1964** [comment] 2018-10-14 02:41
Google Modern Skyblock 3.
Go the Curse site
Go to Files
Left Click the 3.4.2 Mod.
Left Click the Download button on the Top Right and download that.
Scroll down to see the Server File Download.
Install only the items you need for the mod and not the Server stuff, then install everything in the Overrides Folder and those two other files.

**Comment by TheVekter** [comment] 2018-10-14 04:45
This seems to be due to an addon, namely "Extra Utilities Cursed Earth Ritual", being removed from Curseforge. Modpack author will need to find an alternative or a backup, presumably.

**Comment by Draconuuse** [comment] 2018-10-14 07:22
Sorry for being so new on this. I have gotten way to used to the various launchers over the years and don't know how to run this pack now that one little mod is missing from curse/twitch. 

So are you suposed to install these files over a vanilla install or do they include everything you need. is there a way to get twitch to look at the folder and play it for you similar to steam running non steam related games.

Again sorry and thanks for any help.

**Comment by Tkdriverx** [comment] 2018-10-14 16:02
#785

**Comment by Furious1964** [comment] 2018-10-14 21:19
> 
> 
> Sorry for being so new on this. I have gotten way to used to the various launchers over the years and don't know how to run this pack now that one little mod is missing from curse/twitch.
> 
> So are you suposed to install these files over a vanilla install or do they include everything you need. is there a way to get twitch to look at the folder and play it for you similar to steam running non steam related games.
> 
> Again sorry and thanks for any help.

When you use Twitch, create a custom mod profile and then add the files from the Extra Utilities site. You will need both of them and install the larger one first. Remember to NOT install the stuff for the Server.

**Comment by Draconuuse** [comment] 2018-10-15 00:22
> 
> 
> > Sorry for being so new on this. I have gotten way to used to the various launchers over the years and don't know how to run this pack now that one little mod is missing from curse/twitch.
> > So are you suposed to install these files over a vanilla install or do they include everything you need. is there a way to get twitch to look at the folder and play it for you similar to steam running non steam related games.
> > Again sorry and thanks for any help.
> 
> When you use Twitch, create a custom mod profile and then add the files from the Extra Utilities site. You will need both of them and install the larger one first. Remember to NOT install the stuff for the Server.

Ah Thanks Very much appreciated.

**Comment by moofMonkey** [comment] 2018-10-15 17:33
Another workaround:
1) Click "Download" [here](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2607165)
2) Save it somewhere
3) Replace manifest.json contents inside archive with [this](https://pastebin.com/raw/sjVkJGH1)
4) Go to Twitch => Mods => Minecraft => "Create custom profile" tab => import
![image](https://user-images.githubusercontent.com/11695747/46967519-711c3000-d0b9-11e8-8b09-ec060f89a9f6.png)
![image](https://user-images.githubusercontent.com/11695747/46967533-7da08880-d0b9-11e8-9521-692bb0516c81.png)
5) Select zip where you've replaced "manifest.json"
6) Enjoy! :)

**Comment by Eraht** [comment] 2018-10-15 18:05
Adding onto MoofMonkey you can add the missing mod from the server file to the pack

Download the server file [here](https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2607201)
In the mod folder find "exu2cer-1.12-1.0"
Copy that file
After the modpack has been installed via MoofMonkey's manifest replace go to the mod folder inside the modpack folder
paste "exu2cer-1.12-1.0"

After that you'll have a complete modpack again.

**Comment by TheVekter** [comment] 2018-10-16 05:03
I can confirm this works fine. Thanks for the help, guys.

**Closed as completed** 2018-10-16 21:44 UTC
Labels: not pack-related

**Comment by UnhallowedDeath** [comment] 2018-10-16 21:57
How is this not pack related??????? yes the mod is no longer on the launcher but it is being used by the PACK. and because it is being used by the PACK it throws the error which does not allow you to play the PACK. so how can you close a ticket out saying it is not pack related???????

**Comment by TheLimePixel** [comment] 2018-10-16 21:59
Because it's a problem caused by the launcher.

**Comment by TheVekter** [comment] 2018-10-16 22:02
Are you opening a ticket with Twitch/Curseforge to get this fixed? It's impossible to play or download your pack without the launcher or an inconvenient work-around, so it's pretty critical this gets fixed.

**Comment by UnhallowedDeath** [comment] 2018-10-16 22:04
yes but should you be doing something about it regarding the pack like removing the mod from it so its usable again

**Comment by TheLimePixel** [comment] 2018-10-16 22:05
I don't know if they'd do anything about it. It all worked fine until a week ago. This is a change they really shouldn't have done as there are probably many packs that aren't being updated anymore which were affected by this.

**Comment by TheVekter** [comment] 2018-10-16 22:10
I guess the only real thing that can be done is getting in touch with the author of that mod and seeing if they can re-upload it, or finding some way to bypass it and give another way to grant Cursed Earth (which would be very difficult and time consuming). Curseforge might be able to restore the mod if it was accidentally deleted.

**Comment by Firesniper2002** [comment] 2018-10-29 16:51
I am sorry, I am new too, but isn't is possible to remove the mod in a new pack update, for both Modern Skyblock 2 and 3? Wouldn't that solve it?

**Comment by TheVekter** [comment] 2018-10-29 16:59
He would need to find a legit replacement for getting a Drop of Evil or
Cursed Earth that doesn't involve killing wither skeletons, as they can't
spawn until Advanced Resources is complete.

He could just make one of the prerequisite quests grant a Drop of Evil but
idk if he wants to do that or not.

**Comment by Firesniper2002** [comment] 2018-10-29 17:08
But if he removes the mod, it would at least make the two modpacks available for download, and he can put a warning in the description (or something along those lines) about the drop of evil not being available as easy. And either way, cursed earth is not really a bottleneck in this modpack, it just speeds thing up.

**Comment by TheVekter** [comment] 2018-10-30 18:20
I honestly agree that removing it at this point and modifying the quests so
you can get it automatically is probably the best way to handle it, but I
don't know what (if anything) Pixel plans to do to fix this.

**Comment by Firesniper2002** [comment] 2018-10-30 21:26
Hopefully he sees this and decides to fix it, because boy, do I like to play that pack!

**Comment by TheLimePixel** [comment] 2018-10-30 21:28
What nonsense are you guys talking about? It's been fixed for weeks.

**Comment by Firesniper2002** [comment] 2018-10-30 21:30
Yea, that is right for Modern Skyblock 3. Modern Skyblock 2 hasn’t though, and that still fails to download on twitch, unless you got a different way to download that pack (MSB2).

**Comment by Firesniper2002** [comment] 2018-10-30 21:34
It still gives you the 262691 error.

**Comment by TheVekter** [comment] 2018-10-30 21:36
Oh, rad. Thanks Pixel.

**Comment by Firesniper2002** [comment] 2018-10-30 22:07
Would you mind to change that in Modern Skyblock 2, Pixel? I (and probably a lot of other people) would really appreciate that!
