### ISSUE TITLE
Overpowered looting

### ISSUE THREAD

**Issue by sidlo007** [TheLimePixel/Modern-Skyblock-3#294] opened 2018-03-20 19:37 UTC
If I kill an enemy with looting II, I get around a stack of special drop. Is that a bug or intended machanic?

**Comment by b0bst3r** [comment] 2018-03-20 21:15
It's not looting that does it, it's the mega loot helm with luck on it and previous issues brought up have been closed as "working as intended".  If you don't like it remove the helm and replace with one without luck on it.

**Closed as completed by b0bst3r** 2018-03-20 21:15 UTC
