### ISSUE TITLE
3.4.1.3 can't break all  block

### ISSUE THREAD

**Issue by BuGRocK** [TheLimePixel/Modern-Skyblock-3#608] opened 2018-06-17 18:12 UTC
a block and entity like a torch can place and move but can't to break it i try to create a new world

**Comment by progheal** [comment] 2018-06-18 08:52
Duplicate of #604, known issue due to mod incompatible. Temporary solution is to revert to 3.4.1.2.

**Closed as completed** 2018-06-18 20:57 UTC
