### ISSUE TITLE
Crash when entering my world

### ISSUE THREAD

**Issue by NCardCaptor** [TheLimePixel/Modern-Skyblock-3#616] opened 2018-06-22 03:09 UTC
When i enter my world, where i just completed some basic resources quests i got this error

`The game crashed whilst rendering entity in world
The game crashed whilst rendering entity in world
Error: java.lang.NoSuchMethodError: net.minecraftforge.client.ForgeHooksClient.getMatrix(Lnet/minecraft/client/renderer/block/model/ItemTransformVec3f;)Ljavax/vecmath/Matrix4f;`

I can't get the complete crash report from twitch when i click on the "get crash report" button.

Any ideas of how can i fix this ?

**Comment by TheLimePixel** [comment] 2018-06-24 17:41
In the top right corner of the Twitch app, 
...>open folder>crash logs

**Comment by TheLimePixel** [comment] 2018-06-24 18:38
Duplicate of #502

**Closed as completed by TheLimePixel** 2018-06-24 18:38 UTC
Labels: duplicate
