### ISSUE TITLE
Basic Portable Storage quest in Thermal Enhancements bugged

### ISSUE THREAD

**Issue by VortexJD** [TheLimePixel/Modern-Skyblock-3#648] opened 2018-07-08 20:18 UTC
Crafted the basic flux capacitor, reservoir, and satchel.  However, the Satchel component of the quest is not being detected in my inventory.  Playing 3.4.1.4 (latest version AFAIK).  Tried to cheat the item and and still not detected either.  Not sure how to proceed (probably a way to complete in BQ, but I'll have to go search how)

**Comment by Flachdachs** [comment] 2018-07-14 21:40
duplicate of #580 

You can enter this command to resolve the quest `/bq_admin complete 460`.
You will also need to complete numbers 461 to 464 this way.

**Closed as completed** 2018-08-22 20:47 UTC
Labels: fixed in dev
