### ISSUE TITLE
Crash with version 3.4

### ISSUE THREAD

**Issue by purestone9** [TheLimePixel/Modern-Skyblock-3#512] opened 2018-05-08 20:38 UTC
https://pastebin.com/a5v5EF2J

**Comment by MaxNeedsSnacks** [comment] 2018-05-10 13:50
Duplicate of #513 / Azanor/thaumcraft-beta#616, disable the Pech from spawning within the thaumcraft_world.cfg config file

**Closed as completed** 2018-05-22 08:36 UTC
Labels: fixed in dev
